library(downloader)
library(data.table)
library(dplyr)
library(reshape2)
URL <- "https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip"
download.file(URL,"E:/FER i posao/Coursera_Iversity/Data Scientist Specialization/3 Getting and cleaning data/Course project/dataset.zip",mode="wb")
setwd("E:/FER i posao/Coursera_Iversity/Data Scientist Specialization/3 Getting and cleaning data/Course project")
curr_dir <- getwd()
unzip("dataset.zip",exdir="ProjectData")
setwd("./ProjectData")
setwd("./UCI HAR Dataset")
setwd("./test")
subject_test <- read.table("subject_test.txt")
X_test <- read.table("X_test.txt")
Y_test <- read.table("Y_test.txt")
setwd("..")
setwd("./train")
subject_train <- read.table("subject_train.txt")
X_train <- read.table("X_train.txt")
Y_train <- read.table("Y_train.txt")
Xbind <- rbind(X_test,X_train)
Xnames <- c(names(Xbind))
Ybind <- rbind(Y_test,Y_train)
Subbind <- rbind(subject_test,subject_train)
setnames(Subbind,"V1","subject")
setnames(Ybind,"V1","activityNum")
helpbind <- cbind(Ybind,Subbind)
finaldata <- cbind(Xbind,helpbind)
finaldata <- data.table(finaldata)
setkey(finaldata,subject,activityNum)
setwd("..")
features <- read.table("features.txt")
features <- data.table(features)
setnames(features,names(features),c("featureID","featureName"))
features <- features[grepl("mean|std",featureName)]
features$featureCode <- features[,paste0("V",featureID)]
subset_key <- c(key(finaldata),features$featureCode)
finaldata <- finaldata [,subset_key,with=FALSE]
activities <- read.table("activity_labels.txt")
activites <- data.table(activities)
setnames(activities,"V1","activityNum")
setnames(activities,"V2","activityName")
finaldata <- merge(finaldata,activities,by="activityNum")
setkey(finaldata,subject,activityNum,activityName)
finaldata <- data.table(melt(finaldata,key(finaldata),variable.name ="featureCode"))
finaldata <- merge(finaldata, features[,list(featureID, featureCode, featureName)], by="featureCode", all.x=TRUE)
grouped <- group_by(finaldata, subject, activityNum)
mean_table <- summarise(grouped, mean=mean(value))
mean_table <- merge(mean_table,activities,by="activityNum")
mean_table <- cbind(mean_table,features)
write.table(mean_table,"tidy_data.txt",row.names = TRUE)
